/* 
   CREDIT CARD ANALYSIS
  ============================================================
   
   Main goal:
   Understand what is driving revenue, how customers are
   using their cards, and which customer segments stand out.

   Analysis areas:
   1. Revenue & Transaction Performance
   2. Customer Value & Segmentation
   3. Growth & Revenue Concentration
   4. Business Opportunities
   ============================================================ */


/* ============================================================
   PROJECT BLUEPRINT
   ============================================================

   1. REVENUE & TRANSACTION PERFORMANCE

   Start with the overall numbers and then look at revenue
   by card category, expenditure type and transaction method.

   Q1  Overall Revenue & Transaction Performance
   Q2  Revenue by Card Category
   Q3  Revenue by Expenditure Type
   Q4  Revenue by Transaction Method


   2. CUSTOMER VALUE & SEGMENTATION

   Look at which types of customers contribute more revenue
   and identify customers performing above average.

   Q5  Revenue by Profession
   Q6  Revenue by Age Group
   Q7  Customers Above Average Revenue


   3. GROWTH & REVENUE CONCENTRATION

   Check how revenue changes over time and how much revenue
   comes from the highest-value customers.

   Q8  Quarterly Revenue & QoQ Growth
   Q9  Monthly Revenue & MoM Growth
   Q10 Customer Revenue Ranking & Cumulative Revenue


   4. BUSINESS OPPORTUNITIES

   Look deeper into customers and card segments to find
   areas that may be worth focusing on.

   Q11 Top 3 Customers by Profession
   Q12 Card Category × Income Level
   
   SQL used:
   JOIN, GROUP BY, CASE, CTE, aggregate functions,
   RANK(), ROW_NUMBER(), LAG() and window functions.
   
   Database : ccdb
   SQL      : MySQL

   Tables:
   - cc_detail
   - cust_detail

   ============================================================ */

/* ============================================================
   1. REVENUE & TRANSACTION PERFORMANCE
   ============================================================ */


/* Q1. Overall Revenue & Transaction Performance

   Get a quick picture of the overall business.
*/

SELECT
    COUNT(DISTINCT Client_Num) AS Total_Customers,
    SUM(Total_Trans_Amt) AS Total_Revenue,
    SUM(Total_Trans_Ct) AS Total_Transactions,
    SUM(Interest_Earned) AS Total_Interest_Earned,
    ROUND(AVG(Credit_Limit), 2) AS Average_Credit_Limit,
    ROUND(
        SUM(Total_Trans_Amt) / SUM(Total_Trans_Ct),
        2
    ) AS Average_Transaction_Value
FROM cc_detail;


/* ------------------------------------------------------------
   Q2. Revenue by Card Category

   Compare revenue generated by each card category.
*/

SELECT
    Card_Category,
    SUM(Total_Trans_Amt) AS Revenue,
    SUM(Total_Trans_Ct) AS Transactions,
    SUM(Interest_Earned) AS Interest_Earned,
    ROUND(
        SUM(Total_Trans_Amt) * 100.0 /
        (SELECT SUM(Total_Trans_Amt) FROM cc_detail),
        2
    ) AS Revenue_Contribution_Pct
FROM cc_detail
GROUP BY Card_Category
ORDER BY Revenue DESC;


/* ------------------------------------------------------------
   Q3. Revenue by Expenditure Type

   See which spending categories bring in the most revenue.
*/

SELECT
    Exp_Type,
    SUM(Total_Trans_Amt) AS Revenue,
    SUM(Total_Trans_Ct) AS Transactions,
    ROUND(
        SUM(Total_Trans_Amt) /
        SUM(Total_Trans_Ct),
        2
    ) AS Average_Transaction_Value,
    ROUND(
        SUM(Total_Trans_Amt) * 100.0 /
        (SELECT SUM(Total_Trans_Amt) FROM cc_detail),
        2
    ) AS Revenue_Contribution_Pct
FROM cc_detail
GROUP BY Exp_Type
ORDER BY Revenue DESC;


/* ------------------------------------------------------------
   Q4. Revenue by Transaction Method

   Compare revenue and transaction volume across
   transaction methods.
*/

SELECT
    Use_Chip AS Transaction_Method,
    SUM(Total_Trans_Amt) AS Revenue,
    SUM(Total_Trans_Ct) AS Transactions,
    ROUND(
        SUM(Total_Trans_Amt) /
        SUM(Total_Trans_Ct),
        2
    ) AS Average_Transaction_Value,
    RANK() OVER (
        ORDER BY SUM(Total_Trans_Amt) DESC
    ) AS Revenue_Rank
FROM cc_detail
GROUP BY Use_Chip
ORDER BY Revenue_Rank;


/* ============================================================
   2. CUSTOMER VALUE & SEGMENTATION
   ============================================================ */


/* Q5. Revenue by Profession

   Find out which customer professions contribute
   the most revenue.
*/

SELECT
    cd.Customer_Job,
    COUNT(DISTINCT cd.Client_Num) AS Customers,
    SUM(cc.Total_Trans_Amt) AS Revenue,
    SUM(cc.Total_Trans_Ct) AS Transactions,
    ROUND(
        SUM(cc.Total_Trans_Amt) /
        COUNT(DISTINCT cd.Client_Num),
        2
    ) AS Revenue_Per_Customer
FROM cust_detail cd
JOIN cc_detail cc
    ON cd.Client_Num = cc.Client_Num
GROUP BY cd.Customer_Job
ORDER BY Revenue DESC;


/* ------------------------------------------------------------
   Q6. Revenue by Age Group

   Compare revenue across different customer age groups.
*/

SELECT
    CASE
        WHEN Customer_Age < 30 THEN '<30'
        WHEN Customer_Age BETWEEN 30 AND 39 THEN '30-39'
        WHEN Customer_Age BETWEEN 40 AND 49 THEN '40-49'
        WHEN Customer_Age BETWEEN 50 AND 59 THEN '50-59'
        ELSE '60+'
    END AS Age_Group,

    COUNT(DISTINCT cd.Client_Num) AS Customers,
    SUM(cc.Total_Trans_Amt) AS Revenue,
    SUM(cc.Total_Trans_Ct) AS Transactions,

    ROUND(
        SUM(cc.Total_Trans_Amt) /
        COUNT(DISTINCT cd.Client_Num),
        2
    ) AS Revenue_Per_Customer

FROM cust_detail cd
JOIN cc_detail cc
    ON cd.Client_Num = cc.Client_Num

GROUP BY
    CASE
        WHEN Customer_Age < 30 THEN '<30'
        WHEN Customer_Age BETWEEN 30 AND 39 THEN '30-39'
        WHEN Customer_Age BETWEEN 40 AND 49 THEN '40-49'
        WHEN Customer_Age BETWEEN 50 AND 59 THEN '50-59'
        ELSE '60+'
    END

ORDER BY Revenue DESC;


/* ------------------------------------------------------------
   Q7. Customers Above Average Revenue

   Find customers whose revenue is higher than the
   average customer revenue.
*/

WITH customer_revenue AS (
    SELECT
        Client_Num,
        SUM(Total_Trans_Amt) AS Total_Revenue
    FROM cc_detail
    GROUP BY Client_Num
)
SELECT
    Client_Num,
    Total_Revenue
FROM customer_revenue
WHERE Total_Revenue > (
    SELECT AVG(Total_Revenue)
    FROM customer_revenue
)
ORDER BY Total_Revenue DESC;


/* ============================================================
   3. GROWTH & REVENUE CONCENTRATION
   ============================================================ */


/* Q8. Quarterly Revenue & QoQ Growth

   Compare each quarter with the previous quarter.
*/

WITH quarterly_revenue AS (
    SELECT
        current_year,
        Qtr,
        SUM(Total_Trans_Amt) AS Revenue
    FROM cc_detail
    GROUP BY current_year, Qtr
)
SELECT
    current_year,
    Qtr,
    Revenue,
    LAG(Revenue) OVER (
        ORDER BY current_year, Qtr
    ) AS Previous_Quarter_Revenue,
    Revenue -
    LAG(Revenue) OVER (
        ORDER BY current_year, Qtr
    ) AS QoQ_Change
FROM quarterly_revenue
ORDER BY current_year, Qtr;


/* ------------------------------------------------------------
   Q9. Monthly Revenue & MoM Growth

   Check how revenue changes from month to month.
*/

WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(Week_Start_Date, '%Y-%m') AS Month,
        SUM(Total_Trans_Amt) AS Revenue
    FROM cc_detail
    GROUP BY DATE_FORMAT(Week_Start_Date, '%Y-%m')
)
SELECT
    Month,
    Revenue,
    LAG(Revenue) OVER (
        ORDER BY Month
    ) AS Previous_Month_Revenue,
    Revenue -
    LAG(Revenue) OVER (
        ORDER BY Month
    ) AS MoM_Change
FROM monthly_revenue
ORDER BY Month;


/* ------------------------------------------------------------
   Q10. Customer Revenue Ranking & Cumulative Revenue

   Rank customers by revenue and track cumulative revenue.
*/

WITH customer_revenue AS (
    SELECT
        Client_Num,
        SUM(Total_Trans_Amt) AS Total_Revenue
    FROM cc_detail
    GROUP BY Client_Num
)
SELECT
    Client_Num,
    Total_Revenue,

    RANK() OVER (
        ORDER BY Total_Revenue DESC
    ) AS Revenue_Rank,

    SUM(Total_Revenue) OVER (
        ORDER BY Total_Revenue DESC
    ) AS Cumulative_Revenue

FROM customer_revenue
ORDER BY Revenue_Rank;


/* ============================================================
   4. BUSINESS OPPORTUNITIES
   ============================================================ */


/* Q11. Top 3 Customers Within Each Profession

   Find the highest-revenue customers in each profession.
*/

WITH customer_revenue AS (
    SELECT
        cd.Customer_Job,
        cc.Client_Num,
        SUM(cc.Total_Trans_Amt) AS Total_Revenue
    FROM cust_detail cd
    JOIN cc_detail cc
        ON cd.Client_Num = cc.Client_Num
    GROUP BY
        cd.Customer_Job,
        cc.Client_Num
),
ranked_customers AS (
    SELECT
        Customer_Job,
        Client_Num,
        Total_Revenue,
        ROW_NUMBER() OVER (
            PARTITION BY Customer_Job
            ORDER BY Total_Revenue DESC
        ) AS Customer_Rank
    FROM customer_revenue
)
SELECT
    Customer_Job,
    Client_Num,
    Total_Revenue,
    Customer_Rank
FROM ranked_customers
WHERE Customer_Rank <= 3
ORDER BY Customer_Job, Customer_Rank;


/* ------------------------------------------------------------
   Q12. Card Category × Income Level

   Compare card categories across income levels.

   Income is stored as INT in the table, so the actual
   values from the database are used here.
*/

SELECT
    cc.Card_Category,
    cd.Income,
    COUNT(DISTINCT cc.Client_Num) AS Customers,
    SUM(cc.Total_Trans_Amt) AS Revenue,
    SUM(cc.Total_Trans_Ct) AS Transactions,
    ROUND(
        SUM(cc.Total_Trans_Amt) /
        COUNT(DISTINCT cc.Client_Num),
        2
    ) AS Revenue_Per_Customer
FROM cc_detail cc
JOIN cust_detail cd
    ON cc.Client_Num = cd.Client_Num
GROUP BY
    cc.Card_Category,
    cd.Income
ORDER BY Revenue DESC;


/* ============================================================
   END OF ANALYSIS
   ============================================================ */